---
title: "Lung Cancer Prediction"
author: "Lowell Ethan Xavier"
format: html
execute: 
    echo: FALSE
---

```{r}
#| message: FALSE
library(tidyverse)
library(tidybayes)
library(brms)
library(gtsummary)
```

```{r}
lung <- read_csv("data/lung-cancer.csv") |>
  rename(
    index = index,
    patient_id = `Patient Id`,
    age = Age,
    gender = Gender,
    air_pollution = `Air Pollution`,
    alcohol = `Alcohol use`,
    dust_allergy = `Dust Allergy`,
    occupational_hazards = `OccuPational Hazards`,
    genetic_risk = `Genetic Risk`,
    chronic_lung_disease = `chronic Lung Disease`,
    balanced_diet = `Balanced Diet`,
    obesity = Obesity,
    smoking = Smoking,
    passive_smoker = `Passive Smoker`,
    chest_pain = `Chest Pain`,
    coughing_blood = `Coughing of Blood`,
    fatigue = Fatigue,
    weight_loss = `Weight Loss`,
    shortness_of_breath = `Shortness of Breath`,
    wheezing = Wheezing,
    swallowing_difficulty = `Swallowing Difficulty`,
    clubbing_nails = `Clubbing of Finger Nails`,
    frequent_cold = `Frequent Cold`,
    dry_cough = `Dry Cough`,
    snoring = Snoring,
    level = Level
  ) |> mutate(gender = recode(gender, `1` = "Male", `2` = "Female"))
```

```{r}
fit_gender <- brm(
  formula = level ~ gender,
  data = lung,
  family = categorical(),
  silent = 2,
  refresh = 0,
  seed = 9)

fixef(fit_gender)
pp_check(fit_gender)
```

```{r}
fit_gender |> 
  add_epred_draws(newdata = tibble(gender = c("Female", "Male"))) |>
  select(gender, .category, .epred) |>
  filter(.category != "Medium") |>
  ggplot(aes(x = .epred, fill = gender)) +
    geom_histogram(bins = 100) +
    facet_grid(~ .category) +
    scale_x_continuous(
      breaks = c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1),
      labels = scales::percent_format()) +
  labs(title = "Male and Female Posterior for Risk of Lung Cancer", subtitle = "Men are twice as likely as women to get Lung Cancer", fill = "Gender", x = "Posterior Prediction for Lung Cancer") +
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())
```

```{r}
#| cache: TRUE
fit_gauss <- brm(formula = air_pollution ~ level, data = lung, family = gaussian(), refresh = 0, silent = 2, seed = 9)
```

```{r}
new_lung <- fit_gauss |> add_epred_draws(newdata = tibble(level = c("Low", "High", "Medium"))) 
```

```{r}
new_lung |> ggplot(aes(x = .epred, fill = level)) +
  geom_histogram(bins = 1000) +
  labs(
    title = "Posterior for Air Pollution",
    subtitle = "Higher Exposure to Air pollution increases risk to Lung Cancer",
    x = "Air Pollution",
    fill = "Level"
  ) +
  theme_minimal() +
  theme(aspect.ratio = 0.5,
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.title.y = element_blank())
```


